from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import os

class PDFGenerator:
    def generate_report(self, user_data: dict, prediction: str, recommendations: dict, filepath: str):
        c = canvas.Canvas(filepath, pagesize=letter)
        width, height = letter

        # Header
        c.setFont("Helvetica-Bold", 24)
        c.drawString(50, height - 50, "NutriGuide Medical Report")
        
        c.setFont("Helvetica", 12)
        c.drawString(50, height - 80, "Generated by NutriGuide AI")
        
        # User Info
        c.setLineWidth(1)
        c.line(50, height - 90, width - 50, height - 90)
        
        y = height - 120
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y, "Patient Information")
        y -= 20
        c.setFont("Helvetica", 12)
        for key, value in user_data.items():
            c.drawString(50, y, f"{key.replace('_', ' ').title()}: {value}")
            y -= 20
            
        # Prediction
        y -= 20
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y, "Health Assessment")
        y -= 20
        c.setFont("Helvetica", 12)
        c.drawString(50, y, f"Predicted Condition: {prediction}")
        
        # Recommendations
        y -= 40
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y, "Dietary Recommendations")
        y -= 20
        
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, "Recommended Foods:")
        y -= 20
        c.setFont("Helvetica", 12)
        for food in recommendations.get('eat', []):
            c.drawString(70, y, f"- {food}")
            y -= 15
            
        y -= 10
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, "Foods to Avoid:")
        y -= 20
        c.setFont("Helvetica", 12)
        for food in recommendations.get('avoid', []):
            c.drawString(70, y, f"- {food}")
            y -= 15
            
        y -= 20
        c.setFont("Helvetica-Oblique", 10)
        c.drawString(50, y, f"Reason: {recommendations.get('reason', '')}")
        
        c.save()
